[package]
name = "delegate_proxy"
version = "0.1.0"
description = "Delegate Proxy with Transfer Target List"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "delegate_proxy"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "0.30.0"
anchor-spl = "0.30.0"
